# Generated by Django 5.2.7 on 2025-12-15 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fileuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuploads',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
